# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'oscilloscope_gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1161, 970)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBoxConnection = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxConnection.setGeometry(QtCore.QRect(30, 90, 271, 80))
        self.groupBoxConnection.setObjectName("groupBoxConnection")
        self.layoutWidget = QtWidgets.QWidget(self.groupBoxConnection)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 152, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBoxBaud = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBoxBaud.setObjectName("comboBoxBaud")
        self.comboBoxBaud.addItem("")
        self.comboBoxBaud.addItem("")
        self.comboBoxBaud.addItem("")
        self.comboBoxBaud.addItem("")
        self.comboBoxBaud.addItem("")
        self.horizontalLayout.addWidget(self.comboBoxBaud)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBoxConnection)
        self.layoutWidget1.setGeometry(QtCore.QRect(22, 51, 119, 27))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBoxPort = QtWidgets.QComboBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxPort.sizePolicy().hasHeightForWidth())
        self.comboBoxPort.setSizePolicy(sizePolicy)
        self.comboBoxPort.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.comboBoxPort.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBoxPort.setObjectName("comboBoxPort")
        self.comboBoxPort.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBoxPort)
        self.groupBoxData = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxData.setGeometry(QtCore.QRect(30, 210, 271, 80))
        self.groupBoxData.setObjectName("groupBoxData")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBoxData)
        self.layoutWidget2.setGeometry(QtCore.QRect(11, 31, 167, 28))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.spinBoxDataSize = QtWidgets.QSpinBox(self.layoutWidget2)
        self.spinBoxDataSize.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxDataSize.setMinimum(1)
        self.spinBoxDataSize.setProperty("value", 1)
        self.spinBoxDataSize.setObjectName("spinBoxDataSize")
        self.horizontalLayout_3.addWidget(self.spinBoxDataSize)
        self.groupBoxData_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxData_2.setGeometry(QtCore.QRect(30, 340, 271, 140))
        self.groupBoxData_2.setObjectName("groupBoxData_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBoxData_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBoxData_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.spinBoxNumberLines = QtWidgets.QSpinBox(self.groupBoxData_2)
        self.spinBoxNumberLines.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxNumberLines.setMinimum(1)
        self.spinBoxNumberLines.setProperty("value", 1)
        self.spinBoxNumberLines.setObjectName("spinBoxNumberLines")
        self.horizontalLayout_4.addWidget(self.spinBoxNumberLines)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBoxData_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.spinBoxYMax = QtWidgets.QSpinBox(self.groupBoxData_2)
        self.spinBoxYMax.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxYMax.setMinimum(-10000)
        self.spinBoxYMax.setMaximum(10000)
        self.spinBoxYMax.setProperty("value", 1)
        self.spinBoxYMax.setObjectName("spinBoxYMax")
        self.horizontalLayout_5.addWidget(self.spinBoxYMax)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.groupBoxData_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.spinBoxYMin = QtWidgets.QSpinBox(self.groupBoxData_2)
        self.spinBoxYMin.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxYMin.setMinimum(-10000)
        self.spinBoxYMin.setMaximum(10000)
        self.spinBoxYMin.setProperty("value", 0)
        self.spinBoxYMin.setObjectName("spinBoxYMin")
        self.horizontalLayout_6.addWidget(self.spinBoxYMin)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.pushButtonStart = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonStart.setGeometry(QtCore.QRect(30, 804, 89, 71))
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.pushButtonExit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonExit.setGeometry(QtCore.QRect(180, 850, 89, 25))
        self.pushButtonExit.setObjectName("pushButtonExit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1161, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.actionSave_config = QtWidgets.QAction(MainWindow)
        self.actionSave_config.setObjectName("actionSave_config")
        self.actionLoad_config = QtWidgets.QAction(MainWindow)
        self.actionLoad_config.setObjectName("actionLoad_config")
        self.menuFile.addAction(self.actionSave_config)
        self.menuFile.addAction(self.actionLoad_config)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.pushButtonExit.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Oscilloscope"))
        self.groupBoxConnection.setTitle(_translate("MainWindow", "Connection:"))
        self.label.setText(_translate("MainWindow", "Baud rate"))
        self.comboBoxBaud.setItemText(0, _translate("MainWindow", "9600"))
        self.comboBoxBaud.setItemText(1, _translate("MainWindow", "19200"))
        self.comboBoxBaud.setItemText(2, _translate("MainWindow", "38400"))
        self.comboBoxBaud.setItemText(3, _translate("MainWindow", "57600"))
        self.comboBoxBaud.setItemText(4, _translate("MainWindow", "115200"))
        self.label_2.setText(_translate("MainWindow", "Port"))
        self.comboBoxPort.setItemText(0, _translate("MainWindow", "Choose"))
        self.groupBoxData.setTitle(_translate("MainWindow", "Data:"))
        self.label_3.setText(_translate("MainWindow", "data size (Bytes)"))
        self.groupBoxData_2.setTitle(_translate("MainWindow", "Graph:"))
        self.label_4.setText(_translate("MainWindow", "Number of lines"))
        self.label_5.setText(_translate("MainWindow", "y max"))
        self.label_6.setText(_translate("MainWindow", "y min"))
        self.pushButtonStart.setText(_translate("MainWindow", "Start"))
        self.pushButtonExit.setText(_translate("MainWindow", "Exit"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.actionSave_config.setText(_translate("MainWindow", "Save config"))
        self.actionLoad_config.setText(_translate("MainWindow", "Load config"))

